version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hello08  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user_app_again:
    build:
      context: ./ 
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:hello08@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres_data:
