FROM node:20-alpine

WORKDIR /app

COPY ./packege.json ./packege.json
COPY ./packege-lock.json ./packege-lock.json

RUN npm install

COPY . .

ENV DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"

RUN npx prisma migrate dev
RUN npx prisma generate
RUN npm run build

CMD ["npm", start]