FROM oven/bun:1

WORKDIR /usr/src/app

# Install OpenSSL
RUN apt-get update -y && apt-get install -y openssl

# Copy app files
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/http-server ./apps/http-server

# Install dependencies and generate Prisma client
RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:http-server"]
