[package]
name = "week-30-lifetime"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
borse = {version = "1.5", features = ["derive"]}
borsh = "1.5.7"
